//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteelWire.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CumulationReset
    {
        public int ID { get; set; }
        public int UpdateUserID { get; set; }
        public decimal CriticalValue { get; set; }
        public decimal CumulationValue { get; set; }
        public decimal ResetValue { get; set; }
        public decimal RemainValue { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string SteelWireNo { get; set; }
    
        public virtual SecurityUser SecurityUser { get; set; }
    }
}
