//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteelWire.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrillPipeConfig
    {
        public int ID { get; set; }
        public int WorkConfigID { get; set; }
        public decimal DrillPipeWeight { get; set; }
        public decimal DrillPipeLength { get; set; }
        public string DrillPipeName { get; set; }
        public decimal DrillPipeStandLength { get; set; }
        public string DrillPipeType { get; set; }
    
        public virtual WorkConfig WorkConfig { get; set; }
    }
}
