//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteelWire.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityUser
    {
        public SecurityUser()
        {
            this.CumulationReset = new HashSet<CumulationReset>();
            this.CuttingCriticalConfig = new HashSet<CuttingCriticalConfig>();
            this.CuttingCriticalDictionary = new HashSet<CuttingCriticalDictionary>();
            this.Machine = new HashSet<Machine>();
            this.WorkConfig = new HashSet<WorkConfig>();
            this.WorkDictionary = new HashSet<WorkDictionary>();
        }
    
        public int ID { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public bool Checked { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime RegistTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        public virtual ICollection<CumulationReset> CumulationReset { get; set; }
        public virtual ICollection<CuttingCriticalConfig> CuttingCriticalConfig { get; set; }
        public virtual ICollection<CuttingCriticalDictionary> CuttingCriticalDictionary { get; set; }
        public virtual ICollection<Machine> Machine { get; set; }
        public virtual ICollection<WorkConfig> WorkConfig { get; set; }
        public virtual ICollection<WorkDictionary> WorkDictionary { get; set; }
    }
}
