//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteelWire.Business.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SteelWireContext : DbContext
    {
        public SteelWireContext()
            : base("name=SteelWireContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CumulationReset> CumulationReset { get; set; }
        public DbSet<CuttingCriticalConfig> CuttingCriticalConfig { get; set; }
        public DbSet<CuttingCriticalDictionary> CuttingCriticalDictionary { get; set; }
        public DbSet<DrillCollarConfig> DrillCollarConfig { get; set; }
        public DbSet<DrillingDifficulty> DrillingDifficulty { get; set; }
        public DbSet<DrillingType> DrillingType { get; set; }
        public DbSet<DrillPipeConfig> DrillPipeConfig { get; set; }
        public DbSet<Machine> Machine { get; set; }
        public DbSet<SecurityUser> SecurityUser { get; set; }
        public DbSet<WireropeCutRole> WireropeCutRole { get; set; }
        public DbSet<WireropeEfficiency> WireropeEfficiency { get; set; }
        public DbSet<WireropeWorkload> WireropeWorkload { get; set; }
        public DbSet<WorkConfig> WorkConfig { get; set; }
        public DbSet<WorkDictionary> WorkDictionary { get; set; }
    }
}
