//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteelWire.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WirelineInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WirelineInfo()
        {
            this.CriticalRecord = new HashSet<CriticalRecord>();
            this.CutRecord = new HashSet<CutRecord>();
        }
    
        public long ID { get; set; }
        public long UpdateUserID { get; set; }
        public string Number { get; set; }
        public string Diameter { get; set; }
        public string Struct { get; set; }
        public string StrongLevel { get; set; }
        public string TwistDirection { get; set; }
        public decimal OrderLength { get; set; }
        public string UnitSystem { get; set; }
        public System.DateTime UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CriticalRecord> CriticalRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CutRecord> CutRecord { get; set; }
        public virtual SecurityUser SecurityUser { get; set; }
    }
}
