//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteelWire.Business.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkConfig
    {
        public WorkConfig()
        {
            this.DrillCollarConfig = new HashSet<DrillCollarConfig>();
            this.DrillPipeConfig = new HashSet<DrillPipeConfig>();
        }
    
        public int ID { get; set; }
        public int DictionaryID { get; set; }
        public int ConfigUserID { get; set; }
        public decimal FluidDensity { get; set; }
        public decimal ElevatorWeight { get; set; }
        public decimal DrillingShallowHeight { get; set; }
        public decimal DrillingDeepHeight { get; set; }
        public string DrillingType { get; set; }
        public string DrillingDifficulty { get; set; }
        public decimal TripShallowHeight { get; set; }
        public decimal TripDeepHeight { get; set; }
        public int TripCount { get; set; }
        public decimal BushingWeight { get; set; }
        public decimal BushingLength { get; set; }
        public decimal BushingHeight { get; set; }
        public decimal CoringShallowHeight { get; set; }
        public decimal CoringDeepHeight { get; set; }
        public System.DateTime ConfigTime { get; set; }
        public decimal WorkValue { get; set; }
        public long ConfigTimeStamp { get; set; }
    
        public virtual ICollection<DrillCollarConfig> DrillCollarConfig { get; set; }
        public virtual ICollection<DrillPipeConfig> DrillPipeConfig { get; set; }
        public virtual SecurityUser SecurityUser { get; set; }
        public virtual WorkDictionary WorkDictionary { get; set; }
    }
}
